---
- name: Create domain
  win_domain: >
     domain_admin_user='{{ dc_user_admin }}'
     domain_admin_password='{{ dc_password_admin }}'
     dns_domain_name='{{ domain_dnsname }}'
     safe_mode_password='{{ dc_password_safemode }}'
  register: ad

- name: Reboot server
  win_reboot:
  when: ad.changed

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'

- name: Wait for DNS to be available
  win_wait_for:
    port: 53
    delay: 10
    sleep: 5
    timeout: 600