---
- name: Create forrest and base domain
  win_domain: >
     domain_admin_user='{{ dc_user_admin }}'
     domain_admin_password='{{ dc_password_admin }}'
     dns_domain_name='{{ win_domain_dnsname }}'
     safe_mode_password='{{ dc_password_safemode }}'
  register: forrest
  when: create_domain == "Root"

- name: Create a child domain foo.example.com with parent example.com
  microsoft.ad.domain_child:
    dns_domain_name: '{{ win_domain_dnsname }}'
    domain_admin_user: '{{ domainjoin_user_name }}'
    domain_admin_password: '{{ domainjoin_user_pw }}'
    safe_mode_password: '{{ domainjoin_user_pw }}'
  register: subdomain
  when: create_domain == "Sub"

- name: Reboot server
  win_reboot:
  when: forrest.changed or subdomain.changed

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'
  register: dns

- name: Wait for DNS to be available
  win_wait_for:
    port: 53
    delay: 10
    sleep: 5
    timeout: 600

- name: Reboot server
  win_reboot:
  when: dns.changed
