---
- name: Create forrest and base domain
  microsoft.ad.domain: >
     dns_domain_name='{{ dc_domain_dns_name }}'
     safe_mode_password='{{ dc_password_admin }}'
  register: forrest
  when: create_domain == "Root"

- name: Create a child domain
  microsoft.ad.domain_child:
    dns_domain_name: 'dom-{{ dc_domain_dns_name }}' # cannot be servername.domain.tld, obviously
    domain_admin_user: '{{ domain_admin_user }}'
    domain_admin_password: '{{ domain_admin_password }}'
    safe_mode_password: '{{ domain_admin_password }}'
    create_dns_delegation: 'true'
    domain_type: 'child'
    install_dns: 'true'
    parent_domain_name: 'sj.azure'
  register: subdomain
  when: create_domain == "Sub"

- name: Reboot server
  win_reboot:
    test_command: "Get-ADUser -Identity Administrator -Properties *"
  when: forrest.changed or subdomain.changed

- name: Set internal DNS server 
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - '127.0.0.1'
  register: dns
  when: create_domain == "Root"

- name: Wait for DNS to be available
  win_wait_for:
    port: 53
    delay: 10
    sleep: 5
    timeout: 600
  when: create_domain == "Root"

- name: Reboot server
  win_reboot:
    test_command: "Get-ADUser -Identity Administrator -Properties *"
  when: dns.reboot_required
